# Change these first
owner: isolucionco # Your GitHub organization or username, where this repository lives
repo: EstadoIsolucionHosting # The name of this repository

sites:

- name: Adiquim.isolucion.co
url: https://Adiquim.isolucion.co
	
	
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /EstadoIsolucionHosting
  logoUrl: https://isolucion.com/wp-content/uploads/2021/05/isolucion25.png
  name: Pagina de Estado Hosting ISOLUCION
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
   # - title: GitHub
      #href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
