# Change these first
owner: isolucionco # Your GitHub organization or username, where this repository lives
repo: EstadoIsolucionHosting # The name of this repository

sites:

- name: IsolucionProcesos
  url: http://23.102.174.233/IsolucionProcesos/
- name: Adiquim.isolucion.co
  url: https://Adiquim.isolucion.co
- name: Adn.isolucion.co
  url: https://Adn.isolucion.co     
- name: AgrocomercialCagir.isolucion.co
  url: https://AgrocomercialCagir.isolucion.co
- name: AIRTEMP.isolucion.co
  url: https://AIRTEMP.isolucion.co
- name: ALBATEQ.isolucion.co
  url: https://ALBATEQ.isolucion.co
- name: AlcaldiaBarranquilla.isolucion.co
  url: https://AlcaldiaBarranquilla.isolucion.co
- name: AlcaldiaDeManizales.isolucion.co
  url: https://AlcaldiaDeManizales.isolucion.co
- name: AlcaldiaTocancipa.Isolucion.co
  url: https://AlcaldiaTocancipa.Isolucion.co
- name: AlcCajica.isolucion.co
  url: https://AlcCajica.isolucion.co
- name: ALFANET.isolucion.co
  url: https://ALFANET.isolucion.co
- name: alianzatemporales.isolucion.co
  url: https://alianzatemporales.isolucion.co
- name: Alura.isolucion.co
  url: https://Alura.isolucion.co
- name: AMVSA.isolucion.co
  url: https://AMVSA.isolucion.co
- name: angiografia.isolucion.co
  url: https://angiografia.isolucion.co
- name: AON.isolucion.co
  url: https://AON.isolucion.co
- name: ApiIso01.isolucion.co
  url: https://ApiIso01.isolucion.co
- name: apiiso01com.isolucion.com
  url: https://apiiso01com.isolucion.com
- name: ApiIso02.isolucion.co
  url: https://ApiIso02.isolucion.co
- name: ApiIso03.isolucion.co
  url: https://ApiIso03.isolucion.co
- name: ApiIso04.isolucion.co
  url: https://ApiIso04.isolucion.co
- name: apiiso05.isolucion.co
  url: https://apiiso05.isolucion.co
- name: ApiIsoSura.isolucion.co
  url: https://ApiIsoSura.isolucion.co
- name: ApiRiesgosDafpApp01.isolucion.co
  url: https://ApiRiesgosDafpApp01.isolucion.co/swagger/index.html
- name: ApiRiesgosDafpApp01Com.isolucion.com
  url: https://ApiRiesgosDafpApp01Com.isolucion.com/swagger/index.html
- name: ApiRiesgosDafpApp02.isolucion.co
  url: https://ApiRiesgosDafpApp02.isolucion.co/swagger/index.html
- name: ApiRiesgosDafpApp03.isolucion.co
  url: https://ApiRiesgosDafpApp03.isolucion.co/swagger/index.html
- name: ApiRiesgosDafpApp04.isolucion.co
  url: https://ApiRiesgosDafpApp04.isolucion.co/swagger/index.html
- name: ApiRiesgosDafpApp05.isolucion.co
  url: https://ApiRiesgosDafpApp05.isolucion.co/swagger/index.html
- name: ApiRiesgosDafpAppdane.isolucion.co
  url: https://ApiRiesgosDafpAppdane.isolucion.co/swagger/index.html
- name: ApiRiesgosDafpAppIcontec.isolucion.co
  url: http://apiriesgosdafpappicontec.isolucion.co/swagger/index.html
- name: ApiRiesgosDafpAppSura.isolucion.co
  url: https://ApiRiesgosDafpAppSura.isolucion.co/swagger/index.html
- name: Aserfinc.isolucion.co
  url: https://Aserfinc.isolucion.co
- name: Asobancaria.isolucion.co
  url: https://Asobancaria.isolucion.co
- name: atinaenergy.isolucion.co
  url: https://atinaenergy.isolucion.co
- name: AUDIFARMA.isolucion.co
  url: https://AUDIFARMA.isolucion.co
- name: BAGGRIT.isolucion.co
  url: https://BAGGRIT.isolucion.co
- name: BAINCOL.isolucion.co
  url: https://BAINCOL.isolucion.co
- name: BASC.isolucion.co
  url: https://BASC.isolucion.co
- name: bgcol.isolucion.co
  url: https://bgcol.isolucion.co
- name: Bimbo.isolucion.co
  url: https://Bimbo.isolucion.co
- name: Biotronitech.isolucion.co
  url: https://Biotronitech.isolucion.co
- name: Blaskov.Isolucion.co
  url: https://Blaskov.Isolucion.co
- name: bmiseguros.isolucion.co
  url: https://bmiseguros.isolucion.co
- name: bomberofloridablanca.isolucion.co
  url: https://bomberofloridablanca.isolucion.co
- name: bonsetlatinamerica.isolucion.co
  url: https://bonsetlatinamerica.isolucion.co
- name: BRASERV.isolucion.co
  url: https://BRASERV.isolucion.co
- name: BUGORG.isolucion.co
  url: https://BUGORG.isolucion.co
- name: Calima.isolucion.co
  url: https://Calima.isolucion.co
- name: Carex.isolucion.co
  url: https://Carex.isolucion.co
- name: Cartama.isolucion.co
  url: https://Cartama.isolucion.co
- name: CelestinFreinet.isolucion.co
  url: https://CelestinFreinet.isolucion.co
- name: CentralCervecera.isolucion.co
  url: https://CentralCervecera.isolucion.co
- name: CentralCervecera.isolucion.co
  url: https://CentralCervecera.isolucion.co
- name: centromayorcc.isolucion.co
  url: https://centromayorcc.isolucion.co      
- name: Cerescos.isolucion.co
  url: https://Cerescos.isolucion.co
- name: Cesmag.isolucion.co
  url: https://Cesmag.isolucion.co
- name: CIFOODCOLOMBIA.isolucion.co
  url: https://CIFOODCOLOMBIA.isolucion.co
- name: clcgas.isolucion.co
  url: https://clcgas.isolucion.co
- name: COBELEN.isolucion.co
  url: https://COBELEN.isolucion.co
- name: COCESNA.isolucion.co
  url: https://COCESNA.isolucion.co
- name: colegiobennett.isolucion.co
  url: https://colegiobennett.isolucion.co
- name: Colegiojesusmaria.isolucion.co
  url: https://Colegiojesusmaria.isolucion.co
- name: Colegionuevagranada.isolucion.co
  url: https://Colegionuevagranada.isolucion.co
- name: collectcenter.isolucion.co
  url: https://collectcenter.isolucion.co
- name: Combarranquilla.isolucion.co
  url: https://Combarranquilla.isolucion.co
- name: comdatagroup.isolucion.co
  url: https://comdatagroup.isolucion.co
- name: Comercializadora3c.isolucion.co
  url: https://Comercializadora3c.isolucion.co
- name: ComfamiliarRisaralda.isolucion.co
  url: https://ComfamiliarRisaralda.isolucion.co
- name: Comfandi.isolucion.co
  url: https://Comfandi.isolucion.co
- name: Consuerte.isolucion.co
  url: https://Consuerte.isolucion.co
- name: Contactar.isolucion.co
  url: https://Contactar.isolucion.co
- name: COOPEDAC.isolucion.co
  url: https://COOPEDAC.isolucion.co
- name: coopminutodedios.isolucion.co
  url: https://coopminutodedios.isolucion.co
- name: Cooptenjo.isolucion.co
  url: https://Cooptenjo.isolucion.co
- name: Coordinadora.isolucion.co
  url: https://Coordinadora.isolucion.co
- name: CorpAmericana.isolucion.co
  url: https://CorpAmericana.isolucion.co
- name: CORSALUD.isolucion.co
  url: https://CORSALUD.isolucion.co
- name: cruzrojaantioquia.isolucion.co
  url: https://cruzrojaantioquia.isolucion.co
- name: CYPDELR.isolucion.co
  url: https://CYPDELR.isolucion.co
- name: dane.isolucion.co
  url: https://dane.isolucion.co
- name: deliveranceship.isolucion.co
  url: https://deliveranceship.isolucion.co
- name: DemoComercial.isolucion.com
  url: https://DemoComercial.isolucion.com
- name: Domotes.isolucion.co
  url: https://Domotes.isolucion.co
- name: Drypers.isolucion.coo
  url: https://Drypers.isolucion.co
- name: educacionfuturo.isolucion.co
  url: https://educacionfuturo.isolucion.co
- name: ElectroquimicaWest.isolucion.co
  url: https://ElectroquimicaWest.isolucion.co
- name: emcocables.isolucion.co
  url: https://emcocables.isolucion.co
- name: EmpaquetadosElTrece.isolucion.co
  url: https://EmpaquetadosElTrece.isolucion.co
- name: EmpaquetadosElTrece.isolucion.co
  url: https://EmpaquetadosElTrece.isolucion.co
- name: equinorte.isolucion.co
  url: https://equinorte.isolucion.co       
- name: Eterna.isolucion.co
  url: https://Eterna.isolucion.co
- name: Fenalce.isolucion.co
  url: https://Fenalce.isolucion.co
- name: Fiducentral.isolucion.co
  url: https://Fiducentral.isolucion.co
- name: FlagSoluciones.isolucion.co
  url: https://FlagSoluciones.isolucion.co
- name: FONTUR.isolucion.co
  url: https://FONTUR.isolucion.co
- name: fundacionbatuta.isolucion.co
  url: https://fundacionbatuta.isolucion.co
- name: Fundelima.isolucion.co
  url: https://Fundelima.isolucion.co
- name: Gabrica.isolucion.co
  url: https://Gabrica.isolucion.co
- name: GlobalOil.isolucion.co
  url: https://GlobalOil.isolucion.co
- name: GloriaColombia.isolucion.co
  url: https://GloriaColombia.isolucion.co
- name: goldenbusinessclass.isolucion.co
  url: https://goldenbusinessclass.isolucion.co
- name: griffithfoods.isolucion.co
  url: https://griffithfoods.isolucion.co
- name: Grupoafin.isolucion.co
  url: https://Grupoafin.isolucion.co
- name: GrupoAlfa.Isolucion.co
  url: https://GrupoAlfa.Isolucion.co
- name: grupoasd.isolucion.co
  url: https://grupoasd.isolucion.co
- name: GrupoGaleria.isolucion.com
  url: https://GrupoGaleria.isolucion.com
- name: grupohinode.isolucion.co
  url: https://grupohinode.isolucion.co
- name: gruposiderurgico.isolucion.co
  url: https://gruposiderurgico.isolucion.co
- name: Guarne.isolucion.co
  url: https://Guarne.isolucion.co
- name: gyjintegracion.isolucion.co
  url: https://gyjintegracion.isolucion.co
- name: Haceb.isolucion.co
  url: https://Haceb.isolucion.co
- name: harinerapardo.isolucion.co
  url: https://harinerapardo.isolucion.co
- name: Hermanasdominicas.isolucion.co
  url: https://Hermanasdominicas.isolucion.co
- name: hgingenieria.isolucion.co
  url: https://hgingenieria.isolucion.co
- name: iasociadas.isolucion.co
  url: https://iasociadas.isolucion.co
- name: ICCONSTRUCTORA.isolucion.co
  url: https://ICCONSTRUCTORA.isolucion.co
- name: ICCundinamarca.isolucion.co
  url: https://ICCundinamarca.isolucion.co
- name: IMPRESISTEM.isolucion.co
  url: https://IMPRESISTEM.isolucion.co
- name: imsa.isolucion.co
  url: https://imsa.isolucion.co
- name: Ingevias.isolucion.co
  url: https://Ingevias.isolucion.co
- name: INNINGGROUP.isolucion.co
  url: https://INNINGGROUP.isolucion.co
- name: IPFSAS.isolucion.co
  url: https://IPFSAS.isolucion.co
- name: ISIPLAST.isolucion.com
  url: https://ISIPLAST.isolucion.com
- name: Isolucion.Icontec.Org
  url: https://Isolucion.Icontec.Org
- name: itsinfocom.isolucion.co
  url: https://itsinfocom.isolucion.co
- name: jargu.isolucion.co
  url: https://jargu.isolucion.co
- name: KHIRON.isolucion.co
  url: https://KHIRON.isolucion.co
- name: KLISTO.isolucion.co
  url: https://KLISTO.isolucion.co
- name: Koneggui.isolucion.co
  url: https://Koneggui.isolucion.co
- name: KYROVET.isolucion.co
  url: https://KYROVET.isolucion.co
- name: labechavarria.isolucion.co
  url: https://labechavarria.isolucion.co
- name: labmedico.isolucion.co
  url: https://labmedico.isolucion.co
- name: LabQuimClinico.isolucion.co
  url: https://LabQuimClinico.isolucion.co
- name: Lafrancol.isolucion.co
  url: https://Lafrancol.isolucion.co
- name: lameseta.isolucion.co
  url: https://lameseta.isolucion.co
- name: Lasmisiones.isolucion.co
  url: https://Lasmisiones.isolucion.co
- name: LATCALINSA.isolucion.co
  url: https://LATCALINSA.isolucion.co
- name: LCNIdiomas.isolucion.co
  url: https://LCNIdiomas.isolucion.co
- name: letratiempo.isolucion.co
  url: https://letratiempo.isolucion.co
- name: LHA.isolucion.co
  url: https://LHA.isolucion.co
- name: Lhoist.isolucion.co
  url: https://Lhoist.isolucion.co
- name: Lmedick.isolucion.co
  url: https://Lmedick.isolucion.co
- name: LUMLOGISTIC.isolucion.co
  url: https://LUMLOGISTIC.isolucion.co
- name: MACROTICS.isolucion.co
  url: https://MACROTICS.isolucion.co
- name: mercadosMadrid.isolucion.co
  url: https://mercadosMadrid.isolucion.co
- name: mesurametrologia.isolucion.co
  url: https://mesurametrologia.isolucion.co
- name: molinosyopal.isolucion.co
  url: https://molinosyopal.isolucion.co       
- name: Motomecanica.isolucion.co
  url: https://Motomecanica.isolucion.co       
- name: municipioconcordia.isolucion.co
  url: https://municipioconcordia.isolucion.co
- name: mymmanejo.isolucion.co
  url: https://mymmanejo.isolucion.co
- name: naturacert.isolucion.co
  url: https://naturacert.isolucion.co
- name: Novabase.isolucion.co
  url: https://Novabase.isolucion.co
- name: INPROQUIM.isolucion.co
  url: https://INPROQUIM.isolucion.co
- name: Nutreo.isolucion.co
  url: https://Nutreo.isolucion.co
- name: Nutrium.isolucion.co
  url: https://Nutrium.isolucion.co
- name: OmegaEnergy.isolucion.co
  url: https://OmegaEnergy.isolucion.co
- name: ONACORG.isolucion.co
  url: https://ONACORG.isolucion.co
- name: ONELINK.isolucion.co
  url: https://ONELINK.isolucion.co
- name: ONGCVIDESH.isolucion.co
  url: https://ONGCVIDESH.isolucion.co
- name: Orientame.isolucion.co
  url: https://Orientame.isolucion.co
- name: Orientame.isolucion.co
  url: https://Orientame.isolucion.co
- name: Ovosur.isolucion.co
  url: https://Ovosur.isolucion.co
- name: pagosgde.isolucion.co
  url: https://pagosgde.isolucion.co
- name: PISENDE.isolucion.co
  url: https://PISENDE.isolucion.co
- name: PLASTIPACK.isolucion.co
  url: https://PLASTIPACK.isolucion.co
- name: Prebel.isolucion.co
  url: https://Prebel.isolucion.co
- name: Premex.isolucion.co
  url: https://Premex.isolucion.co
- name: Primax.isolucion.co
  url: https://Primax.isolucion.co
- name: Profamilia.isolucion.co
  url: https://Profamilia.isolucion.co
- name: puertodebarranquilla.isolucion.co
  url: https://puertodebarranquilla.isolucion.co
- name: qa.isolucion.co
  url: https://qa.isolucion.co
- name: Radiologosasociados.isolucion.co
  url: https://Radiologosasociados.isolucion.co
- name: ramajudicial.isolucion.co
  url: https://ramajudicial.isolucion.co
- name: roldan.isolucion.co
  url: https://roldan.isolucion.co
- name: saitugs.isolucion.co
  url: https://saitugs.isolucion.co
- name: SanGabrielCajica.isolucion.co
  url: https://SanGabrielCajica.isolucion.co
- name: SBLM.isolucion.co
  url: https://SBLM.isolucion.co
- name: SGC.isolucion.co
  url: https://SGC.isolucion.co
- name: SI18SAS.isolucion.co
  url: https://SI18SAS.isolucion.co
- name: sigo.icontec.org/isolucionv4
  url: https://sigo.icontec.org/isolucionv4
- name: silaba.isolucion.com
  url: https://silaba.isolucion.com
- name: SIMED.isolucion.co
  url: https://SIMED.isolucion.co
- name: Simex.isolucion.co
  url: https://Simex.isolucion.co
- name: sincromotors.isolucion.co
  url: https://sincromotors.isolucion.co
- name: Solobus.isolucion.co
  url: https://Solobus.isolucion.co
- name: STS.isolucion.co
  url: https://STS.isolucion.co
- name: Sulicor.isolucion.co
  url: https://Sulicor.isolucion.co
- name: SupermercadoIbanez.isolucion.co
  url: https://SupermercadoIbanez.isolucion.co
- name: Sura.isolucion.co
  url: https://Sura.isolucion.co
- name: SURTIZORA.isolucion.co
  url: https://SURTIZORA.isolucion.co
- name: SYSTEMGROUP.isolucion.co
  url: https://SYSTEMGROUP.isolucion.co
- name: syz.isolucion.co
  url: https://syz.isolucion.co
- name: TECNAS.isolucion.co
  url: https://TECNAS.isolucion.co
- name: tecnoalsa.isolucion.co
  url: https://tecnoalsa.isolucion.co
- name: TERRAGENE.isolucion.co
  url: https://TERRAGENE.isolucion.co
- name: TEXCOMERCIAL.isolucion.co
  url: https://TEXCOMERCIAL.isolucion.co
- name: tmsyp.isolucion.co
  url: https://tmsyp.isolucion.co
- name: TransportesAlex.isolucion.co
  url: https://TransportesAlex.isolucion.co
- name: Uam.isolucion.co
  url: https://Uam.isolucion.co
- name: UCEVA.isolucion.co
  url: https://UCEVA.isolucion.co
- name: uexternado.isolucion.co
  url: https://uexternado.isolucion.co
- name: UMedellin.isolucion.co
  url: https://UMedellin.isolucion.co
- name: UnidadBPD.isolucion.co
  url: https://UnidadBPD.isolucion.co
- name: UniversidadAmerica.isolucion.co
  url: https://UniversidadAmerica.isolucion.co
- name: Upedagogicanacional.isolucion.co
  url: https://Upedagogicanacional.isolucion.co
- name: USABarranquilla.isolucion.co
  url: https://USABarranquilla.isolucion.co
- name: USergioArboleda.isolucion.co
  url: https://USergioArboleda.isolucion.co
- name: VelezLab.isolucion.co
  url: https://VelezLab.isolucion.co
- name: VIHONCO.isolucion.co
  url: https://VIHONCO.isolucion.co
- name: VPCOM.isolucion.co
  url: https://VPCOM.isolucion.co
- name: ZALTSAS.isolucion.co
  url: https://ZALTSAS.isolucion.co


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /EstadoIsolucionHosting
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Isolucion
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
